services:
  postgres:
    image: postgres:17-alpine
    container_name: clinicfiapp-postgres
    ports:
      - "${POSTGRES_PORT_MAPPING:-5438:5432}"
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-clinicfiapp}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-supersecret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: clinicfiapp-zookeeper
    ports:
      - "${ZOOKEEPER_PORT:-2181:2181}"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: clinicfiapp-kafka
    ports:
      - "${KAFKA_EXTERNAL_PORT:-9092:9092}"
    depends_on:
      - zookeeper
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://${KAFKA_ADVERTISED_HOST:-localhost}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: clinicfiapp-kafka-ui
    ports:
      - "${KAFKA_UI_PORT:-8080:8080}"
    restart: on-failure
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka
      - zookeeper

  cache-redis:
    image: redis:alpine
    container_name: clinicfiapp-redis
    ports:
      - "${REDIS_PORT_MAPPING:-6379:6379}"
    restart: on-failure

  scheduler-service:
    build:
      context: .
      dockerfile: services/scheduler-service/Dockerfile
    container_name: clinicfiapp-scheduler-service
    ports:
      - "${SCHEDULER_PORT_MAPPING:-8081:8081}"
    restart: on-failure
    depends_on:
      - postgres
      - kafka
    environment:
      - SCHEDULER_DB_URL=${SCHEDULER_DB_URL:-jdbc:postgresql://postgres:5432/scheduler_db}
      - SCHEDULER_DB_USER=${SCHEDULER_DB_USER:-clinicfiapp}
      - SCHEDULER_DB_PASSWORD=${SCHEDULER_DB_PASSWORD:-supersecret}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9093}
      - JWT_SECRET=${JWT_SECRET:-segredo_padrao_para_dev}

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    container_name: clinicfiapp-notification-service
    ports:
      - "${NOTIFICATION_PORT_MAPPING:-8082:8082}"
    restart: on-failure
    depends_on:
      - postgres
      - kafka
    environment:
      - NOTIFICATION_DB_URL=${NOTIFICATION_DB_URL:-jdbc:postgresql://postgres:5432/notification_db}
      - NOTIFICATION_DB_USER=${NOTIFICATION_DB_USER:-clinicfiapp}
      - NOTIFICATION_DB_PASSWORD=${NOTIFICATION_DB_PASSWORD:-supersecret}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9093}
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME:-clinicfiapp@gmail.com}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-gcgh vlma lihp czxz}
      - MAIL_SSL_TRUST=${MAIL_SSL_TRUST:-smtp.gmail.com}

  history-service:
    build:
      context: .
      dockerfile: services/history-service/Dockerfile
    container_name: clinicfiapp-history-service
    ports:
      - "${HISTORY_PORT_MAPPING:-8083:8083}"
    restart: on-failure
    depends_on:
      - postgres
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=${HISTORY_DB_URL:-jdbc:postgresql://postgres:5432/history_db}
      - SPRING_DATASOURCE_USERNAME=${HISTORY_DB_USER:-clinicfiapp}
      - SPRING_DATASOURCE_PASSWORD=${HISTORY_DB_PASSWORD:-supersecret}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9093}
      - JWT_SECRET=${JWT_SECRET:-segredo_padrao_para_dev}

volumes:
  postgres_data: