version: '3.8'

services:
  # 1. PostgreSQL (Banco de Dados Único)
  postgres:
    image: postgres:17-alpine  # Atualizado para a versão 17
    container_name: clinicfiap-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. ZooKeeper (Necessário para o Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: clinicfiap-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 3. Kafka (Nosso Broker de Mensagens)
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: clinicfiap-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9094,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

volumes:
  postgres_data: